# CI for openseaChest_LogParser
language: cpp

branches:
  only:
  - master
  - develop

matrix:
  include:
    - os: osx
      compiler: clang
      before_script: 
        - git clone https://github.com/Seagate/opensea-common.git
        - mv opensea-common ../
        - cd Make/gcc
      script: 
        make 
    - os: linux
      sudo: false
      compiler: gcc
      dist: xenial
      before_script: 
        - git clone https://github.com/Seagate/opensea-common.git
        - mv opensea-common ../
        cd Make/gcc
      script: 
        make 
    - os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      before_script: 
        cd "Make\VS.2017\opensea-parser\opensea-parser"
      script: 
        - export PATH=$MSBUILD_PATH:$PATH 
        - MSBuild.exe //p:Configuration=Static-Release //p:Platform=x64

